from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]

def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")

class PortfolioSignalSeparationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.source = (ROOT / "market.js").read_text(encoding="utf-8")

    def test_conviction_does_not_embed_confidence_or_risk_gate(self):
        block = self.source.split("function portfolioConviction(s){", 1)[1].split("\n  function holdingSymbol", 1)[0]
        self.assertNotIn("confidence_score", block)
        self.assertNotIn("risk_gate", block)
        self.assertIn("estimate_momentum_score", block)
        self.assertIn("valuation_signal", block)
        self.assertIn("thesis_direction", block)

    def test_confidence_and_risk_remain_explicit_decision_gates(self):
        action = self.source.split("function portfolioAction(", 1)[1].split("\n  const PORTFOLIO_TARGETS_KEY", 1)[0]
        evidence = self.source.split("function portfolioMoveEvidence(", 1)[1].split("\n  function evaluatePortfolioMove", 1)[0]
        self.assertIn("confidence_score", action)
        self.assertIn("risk_gate", action)
        self.assertIn("confidence_score", evidence)
        self.assertIn("risk_gate", evidence)


class PortfolioOptimizeAlgorithmTests(unittest.TestCase):
    def test_decision_center_prioritizes_signals_without_composite_health_score(self):
        s = read("market.js")
        block = s.split("function renderPortfolioDecisionCenter(", 1)[1].split("\n  function portfolioIntelligence(", 1)[0]
        self.assertIn("const structuralAlert=", block)
        self.assertIn("ranked.forEach(r=>{const k=txt(r.stock.sector); if(k) sectors.set", block)
        self.assertNotIn("const k=txt(r.stock.sector)||'Sem setor'", block)
        self.assertIn("(worst?.resilience??100)<75", block)
        self.assertIn("const stressAlert=!partialCoverage&&(worst?.resilience??100)<75", block)
        self.assertIn("const portfolioBase=total>0?total:analysed", block)
        self.assertIn("const positionAlert=topPositionPct>targets.maxPosition", block)
        self.assertIn("const sectorAlert=(topSector?.pct||0)>targets.maxSector", block)
        self.assertIn("const riskBudgetAlert=riskBudget.hasBreaches", block)
        self.assertIn("pct:value/portfolioBase*100", block)
        self.assertIn("topPosition.value/portfolioBase*100", block)
        self.assertIn("const structuralAlert=positionAlert||sectorAlert||riskBudgetAlert||stressAlert", block)
        self.assertIn("if(positionAlert&&topPosition)", block)
        self.assertIn("if(sectorAlert&&topSector)", block)
        self.assertIn("if(riskBudgetAlert)", block)
        self.assertIn("riskBudget.fit+' · parcial'", block)
        self.assertIn("if(stressAlert&&worst) priorities.push", block)
        self.assertIn(":stressAlert&&worst?{label:", block)
        self.assertIn("worst.resilience+' · parcial'", block)
        self.assertNotIn("(worst?.resilience||100)<75", block)
        self.assertIn("const decisionState=", block)
        self.assertIn("data-vpu-state=", block)
        self.assertIn("<small>Risk Fit</small>", block)
        self.assertNotIn("let health=100", block)
        self.assertNotIn("data-vpu-health=", block)
        self.assertNotIn("${health}/100", block)
        self.assertIn("riskBudget.hasBreaches", block)
        self.assertIn("Risk Budget:", block)
        self.assertIn("Rever os limites excedidos no Risk Budget antes de reforçar posições", block)
        self.assertIn(":riskBudgetAlert?{label:'Rever os limites excedidos no Risk Budget antes de reforçar posições'", block)
        self.assertIn("r.resilience>=75?'is-positive'", s)
        self.assertIn("function renderStressScenario(rows,key,total=0)", s)
        self.assertIn("function renderPortfolioStressTest(rows,total=0)", s)
        self.assertIn("Como reage a parte analisável?", s)
        self.assertIn("Resultado parcial:", s)
        self.assertIn("renderStressScenario(rows,k,total)", s)
        self.assertIn("renderPortfolioStressTest(ranked,total)", s)
        self.assertLess(block.index(":riskBudgetAlert?{label:'Rever os limites excedidos no Risk Budget antes de reforçar posições'"), block.index(":reinforce[0]?{label:"))

    def test_unknown_sector_is_not_treated_as_real_sector_concentration(self):
        s = read("market.js")
        fit = s.split("function portfolioFit(", 1)[1].split("\n  function portfolioFitSummary", 1)[0]
        intelligence = s.split("function portfolioIntelligence(", 1)[1].split("\n  function ", 1)[0]
        self.assertIn("const sector=txt(r.stock?.sector);", fit)
        self.assertIn("const sectorPct=sector?sectorRows.find", fit)
        self.assertNotIn("const sector=txt(r.stock?.sector)||'Sem setor'", fit)
        self.assertIn("for(const r of ranked){ const k=txt(r.stock.sector); if(k) sectors.set", intelligence)

    def test_portfolio_health_does_not_compare_target_fit_across_target_changes(self):
        s = read("market.js")
        self.assertIn("const targetContext=[targets.maxPosition,targets.maxSector,targets.overlap].join('|')", s)
        self.assertIn("const targetIncomplete=total>0&&researchCoverage<35", s)
        self.assertIn("const targetFit=targetIncomplete?null:rawTargetFit", s)
        self.assertIn("targetFit==null?'—':targetFit+'/100'", s)
        self.assertIn("Dados parciais.", s)
        self.assertIn("latest.targetFit==null?'—':Math.round(latest.targetFit)", s)
        self.assertIn("x.targetFit==null?'—':Math.round(x.targetFit)", s)
        self.assertNotIn("targets.maxFactor,targets.maxCurrency,targets.maxRegion,targets.overlap,targets.tilt", s)
        self.assertIn("const comparableTargets=!!prev&&txt(latest.targetContext)&&txt(prev.targetContext)&&latest.targetContext===prev.targetContext", s)
        self.assertIn("const comparableTargetEvidence=!!prev&&txt(latest.targetEvidenceContext)&&txt(prev.targetEvidenceContext)&&latest.targetEvidenceContext===prev.targetEvidenceContext", s)
        self.assertIn("const targetEvidenceContext=ranked.map(r=>[txt(r.stock.ticker).toUpperCase(),txt(r.stock.sector),Number(n(r.portfolioFit?.indirectPct)||0).toFixed(4)].join(':')).filter(Boolean).sort().join('|')", s)
        self.assertIn("targetEvidenceContext,riskContext", s)
        self.assertIn("!comparableTargets?'targets alterados':comparableTargetEvidence?healthDeltaLabel(latest.targetFit,prev.targetFit,false,''):'classificação alterada'", s)
        self.assertIn("Os Portfolio Targets mudaram; o Target Fit não é comparado diretamente.", s)
        self.assertIn("A classificação usada pelo Target Fit mudou; o Target Fit não é comparado diretamente.", s)
        self.assertIn("<h4>Evolução da carteira</h4>", s)
        self.assertIn("const shown=inverse?Math.abs(d).toFixed(1)", s)
        self.assertNotIn("const good=inverse?d<0:d>0; return", s)
        self.assertNotIn("<h4>A carteira está a melhorar?</h4>", s)
        self.assertIn("const riskContext=[targets.maxFactor,targets.maxCurrency,targets.maxRegion].join('|')", s)
        self.assertIn("const comparableRisk=!!prev&&txt(latest.riskContext)&&txt(prev.riskContext)&&latest.riskContext===prev.riskContext&&txt(latest.riskEvidenceContext)&&txt(prev.riskEvidenceContext)&&latest.riskEvidenceContext===prev.riskEvidenceContext", s)
        self.assertIn("const riskEvidenceContext=ranked.map(r=>[txt(r.stock.ticker).toUpperCase(),stockRiskTags(r.stock).slice().sort().join(','),stockCurrency(r.stock),stockRegion(r.stock)].join(':')).filter(Boolean).sort().join('|')", s)
        self.assertIn("riskEvidenceContext,researchContext", s)
        self.assertIn("classificação alterada", s)
        self.assertIn("A classificação de risco mudou; o Risk Fit não é comparado diretamente.", s)
        self.assertIn("const comparableResearch=!!prev&&txt(latest.researchContext)&&txt(prev.researchContext)&&latest.researchContext===prev.researchContext", s)
        self.assertIn("const comparableConviction=!!prev&&txt(latest.convictionContext)&&txt(prev.convictionContext)&&latest.convictionContext===prev.convictionContext", s)
        self.assertIn("const comparableActions=!!prev&&txt(latest.actionContext)&&txt(prev.actionContext)&&latest.actionContext===prev.actionContext", s)
        self.assertIn("const actionContext=actionRows.map(r=>[txt(r.stock.ticker).toUpperCase(),txt(r.action?.key),txt(r.action?.reason)].join(':')).filter(Boolean).sort().join('|')", s)
        self.assertIn("convictionCoverage,actionContext", s)
        self.assertIn("comparableActions?healthDeltaLabel(latest.riskPositions,prev.riskPositions,true):'sinais alterados'", s)
        self.assertIn("const convictionContext=convRows.map(r=>txt(r.stock.ticker).toUpperCase()).filter(Boolean).sort().join('|')", s)
        self.assertIn("const convictionCoverage=portfolioBase>0?convictionWeight/portfolioBase*100:100", s)
        self.assertIn("convicção cobertura alterada", s)
        self.assertIn("O conjunto de posições com convicção calculável mudou", s)
        self.assertIn("conv.cob.", s)
        self.assertIn("const researchContext=ranked.map(r=>txt(r.stock.ticker).toUpperCase()).filter(Boolean).sort().join('|')", s)
        self.assertIn("const researchCoverage=total>0?analysed/total*100:100", s)
        self.assertIn("const portfolioBase=total>0?total:analysed", s)
        self.assertIn("portfolioPct:r.value/portfolioBase*100", s)
        self.assertIn("portfolioFit(r,sectorRows,portfolioBase", s)
        self.assertIn("pct:r.value/portfolioBase*100", s)
        self.assertIn("totalAfter:portfolioBase", s)
        self.assertIn("os excessos observados usam o valor total da carteira como denominador", s)
        self.assertIn("cobertura alterada", s)
        self.assertIn("O conjunto de posições analisáveis mudou desde o snapshot anterior", s)
        self.assertIn("<small>Cobertura</small>", s)
        self.assertIn("<small>Risk Fit</small>", s)
        self.assertIn("riskDelta", s)
        self.assertIn("Os limites do Risk Budget mudaram; o Risk Fit não é comparado diretamente.", s)
        self.assertIn("const portfolioConvictionNow=convictionWeight>0?", s)
        self.assertIn("latest.conviction==null?'—':latest.conviction.toFixed(1)", s)
        self.assertIn("latest.riskFit==null?'—':Math.round(latest.riskFit)", s)
        self.assertIn("x.conviction==null?'—':x.conviction.toFixed(0)", s)
        self.assertNotIn("const convictionWeight=convRows.reduce((sum,r)=>sum+r.value,0)||1", s)

    def test_risk_budget_breach_cannot_be_labelled_healthy(self):
        s = read("market.js")
        block = s.split("function renderRiskBudget(rows,total=0){", 1)[1].split("\n  const PORTFOLIO_STRESS_SCENARIOS", 1)[0]
        self.assertIn("const partialCoverage=total>0&&coverage<35", block)
        self.assertIn("const profile=portfolioRiskProfile(rows,total>0?total:undefined)", block)
        self.assertIn("const factorCoveredValue=rows.reduce", block)
        self.assertIn("stockRiskTags(r.stock).length", block)
        self.assertIn("const factorCoverage=factorCoveredValue/riskBase*100", block)
        self.assertIn("const partialFactorCoverage=factorCoverage<35", block)
        self.assertIn("const incomplete=partialCoverage||partialFactorCoverage||!profile.factors.length||!profile.currencies.length||!profile.regions.length", block)
        self.assertIn("fit=incomplete?null:rawFit", block)
        self.assertIn("const tone=incomplete?'is-warn'", block)
        self.assertIn("const statusLabel=incomplete?'Dados parciais'", block)
        self.assertIn("Classificação incompleta", block)
        self.assertIn("Cobertura insuficiente", block)
        self.assertIn("Cobertura de fatores insuficiente", block)
        self.assertIn("tem classificação de fatores", block)
        self.assertIn("o Risk Fit global fica indisponível", block)
        self.assertIn("return {fit,html,profile,breaches,hasBreaches,incomplete,coverage,factorCoverage}", block)
        self.assertIn("renderRiskBudget(ranked,total)", s)

    def test_inflation_shield_exposes_partial_portfolio_coverage(self):
        s = read("market.js")
        block = s.split("function renderInflationShield(rows,portfolioTotal=0){", 1)[1].split("\n\n  const PORTFOLIO_HEALTH_KEY", 1)[0]
        self.assertIn("const partial=portfolioTotal>0&&coverage<35", block)
        self.assertIn("const status=partial?'Dados parciais'", block)
        self.assertIn("Como reage a parte classificável à inflação?", block)
        self.assertIn("cobertura insuficiente para conclusão global", block)
        self.assertIn("menos de 35% da carteira tiver classificação Inflation Shield", block)
        self.assertIn("renderInflationShield(ranked,total)", s)

    def test_portfolio_ui_treats_risk_fit_as_higher_is_better(self):
        s = read("vestra-portfolio-ui.js")
        self.assertIn("riskFit<65", s)
        self.assertIn("riskFit<85", s)
        self.assertIn("Risk Fit sólido", s)
        self.assertIn("healthBar('Risk Fit',m.risk)", s)
        self.assertNotIn("healthBar('Risco',m.risk,true)", s)
        self.assertIn("maior é melhor", s)

    def test_same_sector_alternatives_use_canonical_move_evaluation(self):
        s = read("market.js")
        block = s.split("const alternatives=[];", 1)[1].split("const alternativesByTicker", 1)[0]
        self.assertIn("mode==='alternative'", s)
        self.assertIn("convictionGain>=5&&convDelta>0&&overlapDelta<1.5&&riskPenalty<5", s)
        self.assertIn("const decision=evaluatePortfolioMove({mode:'alternative'", block)
        self.assertIn("if(!decision.autoEligible) return null", block)
        self.assertNotIn("if(!decision.autoEligible||scoreDelta<3) return null", block)
        self.assertIn("const sameIndustry=!!txt(x.industry)&&txt(x.industry)===txt(r.stock.industry)", block)
        self.assertIn("||a.decision.overlapDelta-b.decision.overlapDelta", block)
        self.assertIn("||a.decision.riskPenalty-b.decision.riskPenalty", block)
        self.assertIn("||Number(b.sameIndustry)-Number(a.sameIndustry)", block)
        self.assertNotIn("||b.scoreDelta-a.scoreDelta", block)
        self.assertNotIn("||b.valuationRank-a.valuationRank", block)
        self.assertNotIn("decision.convictionGain*1.35+scoreDelta*.25", block)
        self.assertNotIn("const rank=decision.convictionGain", block)
        self.assertIn("Convicção +${a.convDelta.toFixed(0)}", s)

    def test_canonical_move_evaluator_owns_shared_eligibility(self):
        s = read("market.js")
        self.assertIn("function portfolioMoveEvidence(stock, conviction=null)", s)
        self.assertIn("function evaluatePortfolioMove({mode='replace'", s)
        self.assertIn("autoEligible=sourceAutomatable&&evidence.strict&&riskBudgetReady&&convictionGain>=2&&convDelta>0&&overlapDelta<2", s)
        self.assertIn("positionPct<=maxPos+1&&sectorPct<=maxSector+1&&riskPenalty<5", s)
        self.assertIn("autoEligible=evidence.reinforceEligible&&riskBudgetReady&&riskPenalty<5", s)
        self.assertIn("mode==='scenario'", s)
        self.assertIn("melhoria de convicção insuficiente", s)
        self.assertIn("aumenta overlap", s)
        self.assertIn("origem apenas para análise manual", s)
        self.assertGreaterEqual(s.count("evaluatePortfolioMove({"), 5)

    def test_rebalancer_consumes_canonical_move_evaluator(self):
        s = read("market.js")
        self.assertIn("const decision=evaluatePortfolioMove({mode:'replace'", s)
        self.assertIn("riskPenalty,diversifies,tiltBonus", s)
        self.assertNotIn("riskPenalty,diversifies,valuationRank,tiltBonus", s)
        self.assertIn("tier:decision.evidence.tier", s)
        self.assertIn("Number(b.autoEligible)-Number(a.autoEligible)", s)
        rebal=s.split("function rebalanceSimulation", 1)[1].split("\n  function renderRebalanceResults", 1)[0]
        self.assertNotIn("decision.evidence.penalty", rebal)
        self.assertIn("const portfolioBase=researchUniverseValue(assets)||analysed", rebal)
        self.assertIn("portfolioPct:r.value/portfolioBase*100", rebal)
        self.assertIn("sectorValue/portfolioBase*100", rebal)
        self.assertIn("totalAfter:portfolioBase", rebal)

    def test_portfolio_candidate_ordering_has_no_composite_fit_score(self):
        s = read("market.js")
        self.assertNotIn("const fitScore=Math.max", s)
        self.assertNotIn("fitScore:dest.fitScore", s)
        self.assertNotIn("r.fitScore.toFixed", s)
        self.assertIn("||b.convictionGain-a.convictionGain", s)
        self.assertIn("||a.overlapDelta-b.overlapDelta", s)
        self.assertIn("||a.riskPenalty-b.riskPenalty", s)
        self.assertIn("||b.sectorHeadroom-a.sectorHeadroom", s)
        self.assertIn("Não existe um score composto de Portfolio Fit", s)

    def test_fresh_capital_ordering_uses_explicit_dimensions_not_composite_score(self):
        s = read("market.js")
        block = s.split("function freshCapitalPlan(amount){", 1)[1].split("\n  function renderFreshCapitalPlan", 1)[0]
        self.assertNotIn("let score=conv+", block)
        self.assertNotIn("b.score-a.score", block)
        self.assertNotIn("score,capacity", block)
        self.assertIn("||b.conv-a.conv", block)
        self.assertIn("||b.sectorHeadroom-a.sectorHeadroom", block)
        self.assertIn("||a.indirect-b.indirect", block)
        self.assertNotIn("||b.valuationRank-a.valuationRank", block)
        self.assertIn("||b.tiltBonus-a.tiltBonus", block)
        self.assertIn("const researchTotal=assets.reduce((sum,a)=>sum+portfolioValue(a),0)", block)
        self.assertIn("const currentBase=researchTotal||analysed", block)
        self.assertIn("portfolioPct:r.value/currentBase*100", block)

    def test_concentration_card_uses_saved_portfolio_targets(self):
        s = read("market.js")
        self.assertIn("const concentrationMaxPos=Math.max(3,Math.min(30,n(portfolioTargets.maxPosition)||10))", s)
        self.assertIn("const concentrationMaxSector=Math.max(10,Math.min(60,n(portfolioTargets.maxSector)||25))", s)
        self.assertIn("if(topPosition&&topPosPct>concentrationMaxPos)", s)
        self.assertIn("if(sectorRows[0]?.pct>concentrationMaxSector)", s)
        self.assertNotIn("if(topPosPct>=15) concentration.push", s)
        self.assertNotIn("if(sectorRows[0]?.pct>=30) concentration.push", s)

    def test_action_map_respects_risk_gate_and_saved_portfolio_targets(self):
        s = read("market.js")
        self.assertIn("function portfolioFit(r, sectorRows, analysed, etfs, targets=loadPortfolioTargets())", s)
        self.assertIn("function researchUniverseValue(assets=portfolioAssets())", s)
        self.assertIn("portfolioIntelligence(rows,researchTotal)", s)
        self.assertIn("const maxPos=Math.max(3,Math.min(30,n(targets?.maxPosition)||10))", s)
        self.assertIn("const maxSector=Math.max(10,Math.min(60,n(targets?.maxSector)||25))", s)
        self.assertIn("const portfolioTargets=loadPortfolioTargets()", s)
        self.assertIn("portfolioFit(r,sectorRows,portfolioBase,etfsForFit,portfolioTargets)", s)
        self.assertIn("const structuralDeterioration=gate==='high'||gate==='severe'||(conviction!=null&&conviction<50)", s)
        self.assertIn("if(structuralDeterioration||gate==='watch') return {key:'review'", s)
        action = s.split("function portfolioAction(", 1)[1].split("\n  const PORTFOLIO_TARGETS_KEY", 1)[0]
        self.assertNotIn("||thesis==='down'", action)
        self.assertNotIn("||estimates==='deteriorating'", action)
        evidence = s.split("function portfolioMoveEvidence(stock, conviction=null)", 1)[1].split("\n  function evaluatePortfolioMove", 1)[0]
        conviction = s.split("function portfolioConviction(s)", 1)[1].split("\n  function holdingSymbol", 1)[0]
        self.assertIn("valuation_signal", conviction)
        self.assertNotIn("valuation_signal", evidence)
        self.assertNotIn("actionableValuation", evidence)
        self.assertIn("const evidenceReady=reliabilityReady&&coverage!=null&&coverage>=65&&critical!=null&&critical>=50;", s)
        self.assertIn("const strict=score!=null&&conf!=null&&conf>=60&&evidenceReady&&gate==='clear';", s)
        self.assertIn("const reinforceEligible=strict&&conv!=null&&conv>=70", s)
        self.assertNotIn("if(positionPct>=15||sectorPct>=35||indirectPct>=4) fit='concentrated'", s)
        self.assertNotIn("else if(positionPct>=10||sectorPct>=28||indirectPct>=2) fit='watch'", s)

    def test_review_priority_is_explicit_and_shared_across_decision_surfaces(self):
        s = read("market.js")
        self.assertIn("function portfolioReviewSignals(r)", s)
        self.assertIn("function comparePortfolioReview(a,b)", s)
        self.assertIn("replace:r?.action?.key==='replace'", s)
        self.assertIn("gateRank:gate==='severe'?3:gate==='high'?2:gate==='watch'?1:0", s)
        self.assertNotIn("thesisDown:", s)
        self.assertNotIn("estimatesDown:", s)
        self.assertNotIn("||Number(y.thesisDown)-Number(x.thesisDown)", s)
        self.assertNotIn("||Number(y.estimatesDown)-Number(x.estimatesDown)", s)
        self.assertIn("||x.conviction-y.conviction", s)
        self.assertIn(".sort(comparePortfolioReview)", s)
        self.assertIn("||comparePortfolioReview(a.r,b.r)", s)
        self.assertIn("activeReview[0].action?.key==='replace'?'Substituir':'Rever'", s)
        self.assertIn("e avaliar substituição", s)
        queue = s.split("function renderResearchQueue(review){", 1)[1].split("\n  function renderPortfolioDecisionCenter", 1)[0]
        decision = s.split("function renderPortfolioDecisionCenter(", 1)[1].split("\n  function portfolioIntelligence(", 1)[0]
        intelligence = s.split("function portfolioIntelligence(rows,total)", 1)[1].split("\n  function buildMultiMovePlan", 1)[0]
        self.assertNotIn("(a.r.conviction??999)-(b.r.conviction??999)", queue)
        self.assertIn("const activeItems=items.filter(x=>x.state.status!=='reviewed'&&x.state.status!=='snoozed')", queue)
        self.assertIn("const visible=activeItems.slice(0,12)", queue)
        self.assertIn("activeItems.length>12", queue)
        self.assertNotIn("items.length>12", queue)
        self.assertIn(".sort(comparePortfolioReview)", decision)
        self.assertIn("const activeReview=review.filter(r=>!['reviewed','snoozed'].includes(researchQueueState(r.stock.ticker,researchReviewSignalKey(r)).status))", decision)
        self.assertIn("function researchReviewSignalKey(r)", s)
        self.assertIn("storedSignal!==currentSignal", s)
        self.assertIn("signalChanged:true", s)
        self.assertIn("data-queue-signal=", queue)
        self.assertIn("setResearchQueueState(row.dataset.queueTicker||'',btn.dataset.queueStatus||'new',row.dataset.queueSignal||'')", s)
        self.assertIn("const next=activeReview[0]?", decision)
        self.assertIn("const partialCoverage=total>0&&coverage<35", decision)
        self.assertIn("const incompleteEvidence=partialCoverage||partialConviction||riskBudget.incomplete", decision)
        self.assertIn("const decisionState=activeReview.length?'Rever':structuralAlert?'Atenção':review.length?'Acompanhar':incompleteEvidence?'Dados parciais':'Estável'", decision)
        self.assertIn("Risk Budget incompleto: faltam classificações de exposição", decision)
        self.assertIn("Cobertura de research insuficiente", decision)
        self.assertIn("Completar research antes de tirar conclusões sobre a carteira", decision)
        self.assertIn("const conviction=convWeight>0?", decision)
        self.assertIn("const convictionCoverage=portfolioBase>0?convWeight/portfolioBase*100:0", decision)
        self.assertIn("const partialConviction=convictionCoverage<35", decision)
        self.assertIn("const incompleteEvidence=partialCoverage||partialConviction||riskBudget.incomplete", decision)
        self.assertIn("data-vpu-conviction-coverage=", decision)
        self.assertIn("Convicção · ${convictionCoverage.toFixed(0)}% coberta", decision)
        self.assertIn("Completar evidência de convicção antes de tirar conclusões globais", decision)
        self.assertIn("conviction==null?'—':partialConviction?conviction.toFixed(1)+' · parcial':conviction.toFixed(1)", decision)
        self.assertNotIn("const convWeight=convRows.reduce((a,r)=>a+r.value,0)||1", decision)
        self.assertIn("const tone=activeReview.length?'is-risk':structuralAlert||review.length||incompleteEvidence?'is-warn':'is-positive'", decision)
        self.assertNotIn("const decisionState=review.length?'Rever'", decision)
        self.assertIn("review.length?{label:'Acompanhar posições já revistas antes de novo reforço'", decision)
        self.assertIn("value:'attention'", decision)
        self.assertIn("function applyActionMapFilter(map,requested='')", s)
        self.assertIn("next==='attention'?['review','replace'].includes(key):key===next", s)
        self.assertIn("applyActionMapFilter(map,value==='all'?'':value)", s)
        self.assertNotIn("const next=review[0]?", decision)
        self.assertIn(".sort(comparePortfolioReview).slice(0,3)", intelligence)

    def test_same_value_scenario_uses_canonical_move_evaluator(self):
        s = read("market.js")
        self.assertIn("const decision=evaluatePortfolioMove({mode:'scenario'", s)
        self.assertIn("const {convDelta,overlapDelta,riskPenalty,autoEligible,warnings}=decision", s)
        self.assertIn("if(convDelta<=0||overlapDelta>=2||riskPenalty>=5) impact='Piora'", s)
        self.assertIn("else if(convDelta>=.5||overlapDelta<=-1) impact='Melhora'", s)
        self.assertIn("const eligibility=autoEligible?'Elegível':decision.evidence.strict?'Manual':'Evidência limitada'", s)
        self.assertNotIn("||!decision.evidence.strict) impact='Piora'", s)
        self.assertIn("Evidência limitada não é tratada como deterioração da carteira", s)
        self.assertIn("const convictionCoverage=portfolioBase>0?convictionWeight/portfolioBase*100:100", s)
        self.assertIn("const scenarioPartial=convictionCoverage<35", s)
        self.assertIn("Convicção analisável", s)
        self.assertIn("% convicção coberta", s)
        self.assertIn("Cobertura insuficiente para interpretar esta média como convicção global da carteira", s)
        self.assertNotIn("Convicção carteira ${x.before.toFixed(1)}", s)

    def test_fresh_capital_allocates_only_strict_candidates_with_cumulative_sector_budget(self):
        s = read("market.js")
        self.assertIn("!['watch','high','severe'].includes(txt(x.risk_gate))", s)
        self.assertIn("const decision=evaluatePortfolioMove({mode:'fresh'", s)
        self.assertIn("const {tier}=decision.evidence", s)
        self.assertIn("const baseEligible=decision.autoEligible", s)
        self.assertIn("const warnings=[...decision.evidence.warnings]", s)
        self.assertNotIn("if(!c.autoEligible||used.has", s)
        self.assertIn("const baselineRisk=portfolioRiskProfile(rows,afterTotal)", s)
        self.assertIn("const riskAddSafe=(stock,amount)=>", s)
        self.assertIn("current>limit ? next<=current+.01 : next<=limit+.01", s)
        self.assertIn("const allocationsByTicker=new Map(), sectorAdds=new Map()", s)
        self.assertIn("const baseEligible=decision.autoEligible", s)
        self.assertIn("const eligible=candidates.filter(c=>c.baseEligible).slice(0,5)", s)
        self.assertNotIn("const eligible=candidates.filter(c=>c.autoEligible).slice(0,5)", s)
        self.assertIn("while(remaining>=50&&progressed)", s)
        self.assertIn("const tranche=Math.min(50,remaining,sectorRoom,positionRoom)", s)
        self.assertIn("applyRiskAdd(cand.stock,tranche)", s)
        self.assertNotIn("const shares=[.5,.3,.2]", s)
        self.assertIn("manual:candidates.filter(x=>!x.baseEligible).slice(0,3)", s)
        self.assertIn("O capital fica por alocar.", s)
        self.assertNotIn("budgetMode='soft budget'", s)

    def test_etf_optimize_compares_like_for_like_without_new_super_score(self):
        s = read("market.js")
        self.assertIn("function sameFundExposure(source,candidate)", s)
        self.assertIn("function fundHoldingsOverlapPct(a,b)", s)
        self.assertIn("function findEtfOptimizeAlternatives(ranked,heldTickers)", s)
        self.assertIn("function renderEtfOptimizeCard(rows)", s)
        self.assertIn("overlap>=30||(sameCategory&&specific)", s)
        self.assertNotIn("overlap>=30||sameCategory", s)
        self.assertIn("txt(candidate?.ticker).toUpperCase().replace(/\\.[A-Z]+$/,'')", s)
        self.assertNotIn("txt(candidate?.ticker).toUpperCase().replace(/.[A-Z]+$/,'')", s)
        self.assertIn("scoreDelta>=3", s)
        self.assertIn("terSaving!=null&&terSaving>=0.05", s)
        self.assertIn("dupDelta!=null&&dupDelta<=-5", s)
        self.assertIn("if(scoreDelta<-2)return null", s)
        self.assertIn("if(terSaving!=null&&terSaving<-0.03)return null", s)
        self.assertIn("if(dupDelta!=null&&dupDelta>10)return null", s)
        self.assertIn("ETF OPTIMIZE · MESMA EXPOSIÇÃO", s)
        self.assertIn("não uma recomendação automática de troca", s)
        self.assertIn("Não altera Vestra Score, Discovery Score nem Portfolio Action", s)
        self.assertNotIn("etfOptimizeScore", s)

    def test_etf_optimize_is_separate_from_equity_portfolio_action(self):
        s = read("market.js")
        action = s.split("function portfolioAction(", 1)[1].split("\n  const PORTFOLIO_TARGETS_KEY", 1)[0]
        self.assertNotIn("etf_score", action)
        self.assertNotIn("findEtfOptimizeAlternatives", action)
        intelligence = s.split("function portfolioIntelligence(rows,total)", 1)[1].split("function buildMultiMovePlan", 1)[0]
        self.assertIn("const etfOptimizeRows=findEtfOptimizeAlternatives(ranked,heldTickers)", intelligence)
        self.assertIn("${etfOptimizeHtml}", intelligence)

    def test_overlap_missing_lookthrough_is_not_treated_as_zero(self):
        s = read("market.js")
        fit = s.split("function portfolioFit(", 1)[1].split("\n  function portfolioFitSummary", 1)[0]
        move = s.split("function evaluatePortfolioMove(", 1)[1].split("\n  function renderRiskBudget", 1)[0]
        self.assertIn("const overlapEvidenceReady=targets?.overlap!=='reduce'||overlapReady;", fit)
        self.assertIn("overlap ETF por classificar", fit)
        self.assertIn("||!overlapEvidenceReady) fit='watch'", fit)
        self.assertIn("const overlapEvidenceReady=targets.overlap!=='reduce'||overlapReady;", move)
        self.assertIn("overlap ETF sem holdings suficientes", move)
        self.assertIn("riskBudgetReady&&overlapEvidenceReady&&riskPenalty<5", move)
        self.assertIn("const overlapReady=heldEtfs.length===etfsForFit.length;", s)
        self.assertIn("const overlapReady=heldEtfs.length===etfs.length;", s)
        self.assertIn("sourceIndirect:currentIndirect,overlapReady", s)
        self.assertIn("sourceIndirect:srcIndirect,overlapReady", s)
        self.assertIn("positionPct,sectorPct,indirect,overlapReady", s)

    def test_automatic_moves_require_factor_classification(self):
        s = read("market.js")
        block = s.split("function evaluatePortfolioMove(", 1)[1].split("\n  function renderRiskBudget", 1)[0]
        self.assertIn("const riskBudgetReady=stockRiskTags(destination).length>0;", block)
        self.assertIn("Risk Budget sem classificação de fatores", block)
        self.assertIn("evidence.reinforceEligible&&riskBudgetReady&&riskPenalty<5", block)
        self.assertIn("sourceAutomatable&&evidence.strict&&riskBudgetReady&&convictionGain>=5", block)
        self.assertIn("return {targets,maxPos,maxSector,evidence,riskBudgetReady,riskPenalty", block)

    def test_risk_budget_penalises_only_incremental_excess(self):
        s = read("market.js")
        block = s.split("function riskBudgetPenalty(", 1)[1].split("\n  function portfolioMoveEvidence", 1)[0]
        self.assertIn("const incrementalExcess=(now,after,limit)=>", block)
        self.assertIn("Math.max(0,after-limit)-Math.max(0,now-limit)", block)
        self.assertNotIn("if(after>maxFactor) penalty+=(after-maxFactor)", block)
        self.assertNotIn("if(curAfter>maxCurrency) penalty+=(curAfter-maxCurrency)", block)
        self.assertNotIn("if(regAfter>maxRegion) penalty+=(regAfter-maxRegion)", block)

    def test_multi_move_plan_never_falls_back_to_worsening_candidate(self):
        s = read("market.js")
        self.assertIn("return !usedDest.has(key)&&r.autoEligible&&cumulativeSectorPct<=maxSector+1", s)
        self.assertNotIn("|| sim.results.find(r=>!usedDest.has", s)
        self.assertIn("const baselineRisk=portfolioRiskProfile(rows,totalValue)", s)
        self.assertIn("const totalValue=researchUniverseValue(assets)||rows.reduce((a,r)=>a+r.value,0)||1", s)
        self.assertIn("const riskMoveSafe=(sourceStock,destination,amount)=>", s)
        self.assertIn("current>limit ? next<=current+.01 : next<=limit+.01", s)
        self.assertIn("const usedDest=new Set(), sectorDeltas=new Map()", s)
        self.assertIn("const projectedOverlap=totalOverlapDelta+r.overlapDelta", s)
        self.assertIn("targets.overlap==='reduce'?projectedOverlap<=0:projectedOverlap<2", s)
        self.assertIn("sectorDeltas.set(srcSector,(sectorDeltas.get(srcSector)||0)-sim.amount)", s)
        self.assertIn("applyRiskMove(sim.source,dest.stock,sim.amount)", s)
        self.assertIn("const sourceSignals=r=>", s)
        self.assertIn("const gateRank=gate==='severe'?3:gate==='high'?2:gate==='watch'?1:0", s)
        self.assertIn("const positionExcess=Math.max(0,positionPct-maxPosition)", s)
        self.assertIn("const sectorExcess=Math.max(0,sectorPct-maxSector)", s)
        self.assertIn("const pressured=gateRank>0||positionExcess>0||sectorExcess>0||lowConviction", s)
        plan = s.split("function buildMultiMovePlan(){", 1)[1].split("\n  function renderMultiMovePlan", 1)[0]
        self.assertNotIn("thesisDown", plan)
        self.assertNotIn("estimatesDown", plan)
        self.assertIn("const planSources=rows.filter(r=>!isFund(r.stock)", s)
        self.assertIn("||b.sourceSignals.positionExcess-a.sourceSignals.positionExcess", s)
        self.assertIn("||b.sourceSignals.sectorExcess-a.sourceSignals.sectorExcess", s)
        self.assertIn("const queue=sources.slice(0,6)", s)
        self.assertNotIn("const sourcePressure=r=>", s)
        self.assertNotIn("const fallback=planSources.slice()", s)
        self.assertNotIn("const queue=(sources.length?sources:fallback)", s)
        self.assertIn("Plano indicativo e conservador", s)

if __name__ == "__main__":
    unittest.main(verbosity=2)
