from pathlib import Path

p=Path('market.js')
s=p.read_text()
anchor='''  function portfolioIntelligence(rows,total){\n'''
insert='''  function portfolioAction(stock, alternativesByTicker){\n    const conviction=portfolioConviction(stock);\n    const gate=txt(stock?.risk_gate);\n    const valuation=txt(stock?.valuation_signal);\n    const thesis=txt(stock?.thesis_direction);\n    const estimates=txt(stock?.estimate_signal);\n    const conf=n(stock?.confidence_score);\n    const alt=alternativesByTicker?.get?.(txt(stock?.ticker).toUpperCase())||null;\n    const reasons=[];\n    if(gate==='severe'||gate==='high') reasons.push(`Risk Gate ${gate}`);\n    if(thesis==='down') reasons.push('tese a deteriorar');\n    if(estimates==='deteriorating') reasons.push('expectativas a piorar');\n    if(valuation==='overvalued') reasons.push('valuation exigente');\n    if(valuation==='undervalued') reasons.push('margem de segurança');\n    if(thesis==='up') reasons.push('tese a melhorar');\n    if(estimates==='improving') reasons.push('expectativas a melhorar');\n    if(conf!=null&&conf<60) reasons.push('confiança limitada');\n    if(alt && (gate==='high'||gate==='severe'||(conviction!=null&&conviction<50))) return {key:'replace',label:'Substituir',tone:'risk',reason:`${reasons[0]||'convicção fraca'} · alternativa ${alt.to.ticker} superior`};\n    if(gate==='high'||gate==='severe'||thesis==='down'||estimates==='deteriorating'||(conviction!=null&&conviction<50)) return {key:'review',label:'Rever',tone:'risk',reason:reasons.slice(0,2).join(' · ')||'convicção baixa'};\n    if(conviction!=null&&conviction>=70&&conf!=null&&conf>=60&&!['overvalued','uncertain'].includes(valuation)) return {key:'reinforce',label:'Reforçar',tone:'positive',reason:reasons.slice(0,2).join(' · ')||'convicção elevada'};\n    return {key:'hold',label:'Manter',tone:'neutral',reason:reasons.slice(0,2).join(' · ')||'tese sem alteração material'};\n  }\n\n'''
if 'function portfolioAction(' not in s:
    s=s.replace(anchor,insert+anchor)

old='''    const alternatives=[];\n    for(const r of weak){\n      const curScore=n(r.stock.score); if(!txt(r.stock.sector)||curScore==null) continue;\n      const cand=M.stocks.filter(x=>!isFund(x)&&!heldTickers.has(txt(x.ticker).toUpperCase().replace(/\\.[A-Z]+$/,''))&&txt(x.sector)===txt(r.stock.sector)&&n(x.score)!=null&&n(x.score)>=curScore+8&&n(x.confidence_score)>=60&&!['high','severe'].includes(txt(x.risk_gate))&&txt(x.valuation_signal)!=='overvalued'&&txt(x.estimate_signal)!=='deteriorating')\n        .sort((a,b)=>(portfolioConviction(b)||0)-(portfolioConviction(a)||0))[0];\n      if(cand) alternatives.push({from:r.stock,to:cand,delta:n(cand.score)-curScore});\n      if(alternatives.length>=3) break;\n    }\n'''
new=old+'''    const alternativesByTicker=new Map(alternatives.map(a=>[txt(a.from.ticker).toUpperCase(),a]));\n    const actionRows=ranked.map(r=>({...r,action:portfolioAction(r.stock,alternativesByTicker)}));\n    const actionOrder={replace:0,review:1,reinforce:2,hold:3};\n    actionRows.sort((a,b)=>(actionOrder[a.action.key]??9)-(actionOrder[b.action.key]??9)||(b.value-a.value));\n    const actionCounts=actionRows.reduce((acc,r)=>{acc[r.action.key]=(acc[r.action.key]||0)+1;return acc;},{});\n'''
if 'const alternativesByTicker=' not in s:
    s=s.replace(old,new)

old2='''    return `<div class="market-detail-card"><div class="market-perspective-head"><div><small>PORTFOLIO INTELLIGENCE</small><h4>Prioridades da carteira</h4></div><span class="market-data-age">${Math.round(analysed/(total||analysed)*100)}% coberto</span></div><p>Convicção combina Score Vestra, confiança, valuation, expectativas e Risk Gate. É uma priorização de research — não uma ordem de compra ou venda.</p></div>\n      <div class="market-detail-card"><h4>Candidatos a reforço</h4>${compactRows(reinforce,r=>`Convicção ${Math.round(r.conviction)}/100 · ${txt(r.stock.valuation_signal)||'valuation sem sinal'}`)}</div>\n'''
new2='''    const actionMapHtml=`<div class="market-detail-card market-action-map"><div class="market-perspective-head"><div><small>ACTION MAP</small><h4>Mapa da carteira</h4></div><span class="market-data-age">${actionRows.length} posições</span></div><div class="market-action-summary"><span class="is-positive">Reforçar ${actionCounts.reinforce||0}</span><span>Manter ${actionCounts.hold||0}</span><span class="is-warn">Rever ${actionCounts.review||0}</span><span class="is-risk">Substituir ${actionCounts.replace||0}</span></div><div class="market-action-list">${actionRows.slice(0,12).map(r=>`<button type="button" class="market-action-row" data-market-ticker="${esc(r.stock.ticker)}"><span><strong>${esc(r.stock.ticker)}</strong><small>${esc(r.action.reason)}</small></span><em class="market-action-badge market-action-badge--${r.action.tone}">${esc(r.action.label)}</em></button>`).join('')}</div>${actionRows.length>12?`<details class="market-detail-disclosure"><summary>Ver mais ${actionRows.length-12} posições</summary><div class="market-action-list">${actionRows.slice(12).map(r=>`<button type="button" class="market-action-row" data-market-ticker="${esc(r.stock.ticker)}"><span><strong>${esc(r.stock.ticker)}</strong><small>${esc(r.action.reason)}</small></span><em class="market-action-badge market-action-badge--${r.action.tone}">${esc(r.action.label)}</em></button>`).join('')}</div></details>`:''}<p class="market-case-note">Classificação de research baseada em dados atuais; não é uma ordem automática de compra ou venda.</p></div>`;\n\n    return `<div class="market-detail-card"><div class="market-perspective-head"><div><small>PORTFOLIO INTELLIGENCE</small><h4>Prioridades da carteira</h4></div><span class="market-data-age">${Math.round(analysed/(total||analysed)*100)}% coberto</span></div><p>Convicção combina Score Vestra, confiança, valuation, expectativas e Risk Gate. É uma priorização de research — não uma ordem de compra ou venda.</p></div>\n      ${actionMapHtml}\n      <div class="market-detail-card"><h4>Candidatos a reforço</h4>${compactRows(reinforce,r=>`Convicção ${Math.round(r.conviction)}/100 · ${txt(r.stock.valuation_signal)||'valuation sem sinal'}`)}</div>\n'''
if 'market-action-map' not in s:
    s=s.replace(old2,new2)
p.write_text(s)

p=Path('market.css')
css=p.read_text()
block='''\n/* v4.9 — Portfolio Action Map */\n.market-action-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:10px 0}.market-action-summary span{padding:7px 6px;border-radius:10px;background:var(--card2);border:1px solid var(--line);font-size:10px;font-weight:850;text-align:center;color:var(--text2)}.market-action-summary .is-positive{background:rgba(73,180,103,.10);color:#34764a}.market-action-summary .is-warn{background:rgba(210,174,101,.13);color:#7d6734}.market-action-summary .is-risk{background:rgba(229,88,77,.10);color:#9b4b44}.market-action-list{display:grid;gap:7px}.market-action-row{width:100%;border:1px solid var(--line2);background:var(--item-bg);border-radius:14px;padding:10px 11px;display:flex;align-items:center;justify-content:space-between;gap:10px;text-align:left;color:var(--text);cursor:pointer}.market-action-row>span{min-width:0}.market-action-row strong{display:block;font-size:13px}.market-action-row small{display:block;color:var(--text2);font-size:10px;line-height:1.35;margin-top:2px;white-space:normal}.market-action-badge{font-style:normal;flex:0 0 auto;border-radius:999px;padding:6px 9px;font-size:10px;font-weight:900;border:1px solid var(--line);background:var(--card2);color:var(--text2)}.market-action-badge--positive{background:rgba(73,180,103,.12);color:#34764a;border-color:rgba(73,180,103,.2)}.market-action-badge--risk{background:rgba(229,88,77,.10);color:#9b4b44;border-color:rgba(229,88,77,.18)}@media(max-width:520px){.market-action-summary{grid-template-columns:repeat(2,1fr)}}\n'''
if '/* v4.9 — Portfolio Action Map */' not in css:
    css+=block
p.write_text(css)

p=Path('README.md')
r=p.read_text()
head='''## Vestra v4.9 — Portfolio Action Map\n\n- Novo mapa por posição em As minhas posições: Reforçar / Manter / Rever / Substituir.\n- A classificação usa Convicção, Confidence Engine, valuation, estimate momentum, thesis direction, Risk Gate e alternativas já identificadas.\n- “Substituir” só aparece quando a posição está materialmente fraca e existe uma alternativa do mesmo setor já filtrada como superior.\n- Cada linha mostra a razão principal e abre diretamente o dossier da posição.\n- É uma classificação de research, não uma ordem automática de compra/venda.\n- PWA cache: `vestra-cache-v44`.\n\n'''
if not r.startswith('## Vestra v4.9'):
    r=head+r
p.write_text(r)

p=Path('sw.js')
w=p.read_text().replace('/* Vestra — Service Worker v4.8 */','/* Vestra — Service Worker v4.9 */').replace('vestra-cache-v43','vestra-cache-v44')
p.write_text(w)
