from pathlib import Path

p=Path('market.js')
s=p.read_text()

anchor="""  function renderMultiMovePlan(plan){\n    if(!plan?.moves?.length) return '<p class=\"market-case-note\">Não encontrei um plano multi-movimento suficientemente robusto com os dados atuais.</p>';\n"""
if anchor not in s:
    raise SystemExit('renderMultiMovePlan anchor missing')
s=s.replace(anchor,"""  function renderMultiMovePlan(plan){\n    if(!plan?.moves?.length) return '<p class=\"market-case-note\">Não encontrei um plano automático robusto. Experimenta o Rebalancer manual: a Vestra agora mostra candidatos aceitáveis com alertas em vez de esconder tudo.</p>';\n""",1)

old="""    const universe=M.stocks.filter(x=>!isFund(x)&&txt(x.ticker).toUpperCase()!==source&&n(x.score)!=null&&n(x.confidence_score)>=60&&!['high','severe'].includes(txt(x.risk_gate))&&txt(x.valuation_signal)!=='overvalued'&&txt(x.estimate_signal)!=='deteriorating');\n    const ranked=universe.map(stock=>{\n"""
new="""    const universe=M.stocks.filter(x=>!isFund(x)&&txt(x.ticker).toUpperCase()!==source&&n(x.score)!=null&&!['high','severe'].includes(txt(x.risk_gate)));\n    const ranked=universe.map(stock=>{\n"""
if old not in s: raise SystemExit('rebalance universe anchor missing')
s=s.replace(old,new,1)

old="""      const fitScore=conv-penalty+diversityBonus+valuationBonus+tiltBonus;\n      return {stock,conv,convDelta,fitScore,positionPct,sectorPct,indirect,overlapDelta:indirect-srcIndirect,existing:!!existing,targets};\n    }).filter(Boolean).sort((a,b)=>b.fitScore-a.fitScore).slice(0,5);\n"""
new="""      const conf=n(stock.confidence_score);\n      const valuation=txt(stock.valuation_signal), estimates=txt(stock.estimate_signal);\n      const strict=conf!=null&&conf>=60&&valuation!=='overvalued'&&estimates!=='deteriorating';\n      const acceptable=(conf==null||conf>=45)&&!(valuation==='overvalued'&&estimates==='deteriorating');\n      let evidencePenalty=0; const warnings=[];\n      if(conf==null){ evidencePenalty+=7; warnings.push('confiança sem score'); }\n      else if(conf<60){ evidencePenalty+=(60-conf)*.35+3; warnings.push(`confiança ${Math.round(conf)}`); }\n      if(valuation==='overvalued'){ evidencePenalty+=9; warnings.push('valuation exigente'); }\n      else if(valuation==='uncertain'){ evidencePenalty+=3; warnings.push('valuation incerto'); }\n      if(estimates==='deteriorating'){ evidencePenalty+=8; warnings.push('expectativas a piorar'); }\n      const tier=strict?'preferred':acceptable?'acceptable':'research';\n      if(tier==='research') evidencePenalty+=12;\n      const fitScore=conv-penalty+diversityBonus+valuationBonus+tiltBonus-evidencePenalty-riskBudgetPenalty(stock,rows,move,analysed,src.stock);\n      return {stock,conv,convDelta,fitScore,positionPct,sectorPct,indirect,overlapDelta:indirect-srcIndirect,existing:!!existing,targets,tier,warnings};\n    }).filter(Boolean).sort((a,b)=>{ const rank={preferred:0,acceptable:1,research:2}; return (rank[a.tier]-rank[b.tier])||b.fitScore-a.fitScore; }).slice(0,5);\n"""
if old not in s: raise SystemExit('rebalance ranking anchor missing')
s=s.replace(old,new,1)

old="""    if(!sim?.results?.length) return '<p class=\"market-case-note\">Sem destinos elegíveis com os filtros atuais.</p>';\n    const t=loadPortfolioTargets();\n    return `<div class=\"market-target-summary\">Limites: posição ${t.maxPosition}% · setor ${t.maxSector}% · ${t.overlap==='reduce'?'reduzir overlap':'overlap neutro'} · ${esc(t.tilt)}</div><div class=\"market-rebalance-list\">${sim.results.map((r,i)=>`<button type=\"button\" class=\"market-rebalance-row\" data-market-ticker=\"${esc(r.stock.ticker)}\"><span class=\"market-rebalance-rank\">${i+1}</span><span><strong>${esc(r.stock.ticker)} · ${esc(r.stock.name||'')}</strong><small>${r.existing?'Já em carteira':'Nova posição'} · conv. ${Math.round(r.conv)} · peso após ${r.positionPct.toFixed(1)}% · setor ${r.sectorPct.toFixed(0)}%</small><small>Δ convicção carteira ${r.convDelta>=0?'+':''}${r.convDelta.toFixed(2)} · overlap ${r.overlapDelta>=0?'+':''}${r.overlapDelta.toFixed(1)} pp</small></span><em>${r.fitScore.toFixed(0)}</em></button>`).join('')}</div>`;\n"""
new="""    if(!sim?.results?.length) return '<p class=\"market-case-note\">Sem candidatos sequer para research. Revê o universo de dados ou os Portfolio Targets.</p>';\n    const t=loadPortfolioTargets();\n    const tierLabel=r=>r.tier==='preferred'?'Preferido':r.tier==='acceptable'?'Aceitável':'Research';\n    return `<div class=\"market-target-summary\">Limites: posição ${t.maxPosition}% · setor ${t.maxSector}% · ${t.overlap==='reduce'?'reduzir overlap':'overlap neutro'} · ${esc(t.tilt)}</div><div class=\"market-rebalance-list\">${sim.results.map((r,i)=>`<button type=\"button\" class=\"market-rebalance-row\" data-market-ticker=\"${esc(r.stock.ticker)}\"><span class=\"market-rebalance-rank\">${i+1}</span><span><strong>${esc(r.stock.ticker)} · ${esc(r.stock.name||'')}</strong><small>${tierLabel(r)} · ${r.existing?'já em carteira':'nova posição'} · conv. ${Math.round(r.conv)} · peso após ${r.positionPct.toFixed(1)}% · setor ${r.sectorPct.toFixed(0)}%</small><small>Δ convicção ${r.convDelta>=0?'+':''}${r.convDelta.toFixed(2)} · overlap ${r.overlapDelta>=0?'+':''}${r.overlapDelta.toFixed(1)} pp${r.warnings?.length?' · ⚠ '+esc(r.warnings.slice(0,2).join(' · ')):''}</small></span><em>${r.fitScore.toFixed(0)}</em></button>`).join('')}</div>`;\n"""
if old not in s: raise SystemExit('render rebalance anchor missing')
s=s.replace(old,new,1)

old="""    const universe=M.stocks.filter(x=>!isFund(x)&&n(x.score)!=null&&n(x.confidence_score)>=60&&!['high','severe'].includes(txt(x.risk_gate))&&txt(x.valuation_signal)!=='overvalued'&&txt(x.estimate_signal)!=='deteriorating');\n    const candidates=universe.map(stock=>{\n"""
new="""    const universe=M.stocks.filter(x=>!isFund(x)&&n(x.score)!=null&&!['high','severe'].includes(txt(x.risk_gate)));\n    const candidates=universe.map(stock=>{\n"""
if old not in s: raise SystemExit('fresh universe anchor missing')
s=s.replace(old,new,1)

old="""      const posCapacity=Math.max(0,afterTotal*maxPos/100-existingValue), sectorCapacity=Math.max(0,afterTotal*maxSector/100-sectorValue), capacity=Math.min(posCapacity,sectorCapacity,fresh);\n      if(capacity<50) return null;\n      let score=conv+portfolioTiltBonus(stock,targets.tilt);\n      if(txt(stock.valuation_signal)==='undervalued') score+=4; else if(txt(stock.valuation_signal)==='fair') score+=1;\n"""
new="""      const strictPosCapacity=Math.max(0,afterTotal*maxPos/100-existingValue), strictSectorCapacity=Math.max(0,afterTotal*maxSector/100-sectorValue);\n      const softPosCapacity=Math.max(0,afterTotal*(maxPos+3)/100-existingValue), softSectorCapacity=Math.max(0,afterTotal*(maxSector+5)/100-sectorValue);\n      let capacity=Math.min(strictPosCapacity,strictSectorCapacity,fresh), budgetMode='within targets';\n      if(capacity<50){ capacity=Math.min(softPosCapacity,softSectorCapacity,fresh); budgetMode='soft budget'; }\n      if(capacity<50) return null;\n      const conf=n(stock.confidence_score), valuation=txt(stock.valuation_signal), estimates=txt(stock.estimate_signal);\n      const strict=conf!=null&&conf>=60&&valuation!=='overvalued'&&estimates!=='deteriorating'&&budgetMode==='within targets';\n      const acceptable=(conf==null||conf>=45)&&!(valuation==='overvalued'&&estimates==='deteriorating');\n      const tier=strict?'preferred':acceptable?'acceptable':'research';\n      const warnings=[]; let score=conv+portfolioTiltBonus(stock,targets.tilt);\n      if(conf==null){ score-=7; warnings.push('confiança sem score'); } else if(conf<60){ score-=(60-conf)*.35+3; warnings.push(`confiança ${Math.round(conf)}`); }\n      if(valuation==='overvalued'){ score-=9; warnings.push('valuation exigente'); }\n      if(estimates==='deteriorating'){ score-=8; warnings.push('expectativas a piorar'); }\n      if(budgetMode==='soft budget'){ score-=6; warnings.push('excede objetivo ligeiramente'); }\n      if(tier==='research') score-=12;\n      if(valuation==='undervalued') score+=4; else if(valuation==='fair') score+=1;\n"""
if old not in s: raise SystemExit('fresh capacity anchor missing')
s=s.replace(old,new,1)

old="""      return {stock,conv,score,capacity,existingValue,sector,sectorValue,indirect};\n    }).filter(Boolean).sort((a,b)=>b.score-a.score);\n"""
new="""      score-=riskBudgetPenalty(stock,rows,Math.min(capacity,fresh),afterTotal,null);\n      return {stock,conv,score,capacity,existingValue,sector,sectorValue,indirect,tier,warnings,budgetMode};\n    }).filter(Boolean).sort((a,b)=>{ const rank={preferred:0,acceptable:1,research:2}; return (rank[a.tier]-rank[b.tier])||b.score-a.score; });\n"""
if old not in s: raise SystemExit('fresh ranking anchor missing')
s=s.replace(old,new,1)

old="""    if(!plan?.allocations?.length) return '<p class=\"market-case-note\">Não encontrei destinos robustos dentro dos objetivos atuais.</p>';\n    return `<div class=\"market-fresh-summary\"><strong>${euro(plan.allocated)} distribuídos</strong><span>Convicção ponderada ${plan.currentConv.toFixed(1)} → ${plan.afterConv.toFixed(1)}${plan.remaining>=50?` · ${euro(plan.remaining)} ficam por alocar`:''}</span></div><div class=\"market-fresh-list\">${plan.allocations.map((x,i)=>`<button type=\"button\" class=\"market-fresh-row\" data-market-ticker=\"${esc(x.stock.ticker)}\"><span class=\"market-rebalance-rank\">${i+1}</span><span><strong>${esc(x.stock.ticker)} · ${esc(x.stock.name||'')}</strong><small>${euro(x.amount)} · ${x.existingValue>0?'reforço':'nova posição'} · conv. ${Math.round(x.conv)} · peso ${x.positionPct.toFixed(1)}% · setor ${x.sectorPct.toFixed(0)}%</small></span><em>${x.score.toFixed(0)}</em></button>`).join('')}</div>`;\n"""
new="""    if(!plan?.allocations?.length) return '<p class=\"market-case-note\">Não encontrei candidatos mesmo após relaxar os filtros. Revê os objetivos ou a cobertura do universo.</p>';\n    const tierLabel=x=>x.tier==='preferred'?'Preferido':x.tier==='acceptable'?'Aceitável':'Research';\n    return `<div class=\"market-fresh-summary\"><strong>${euro(plan.allocated)} distribuídos</strong><span>Convicção ponderada ${plan.currentConv.toFixed(1)} → ${plan.afterConv.toFixed(1)}${plan.remaining>=50?` · ${euro(plan.remaining)} ficam por alocar`:''}</span></div><div class=\"market-fresh-list\">${plan.allocations.map((x,i)=>`<button type=\"button\" class=\"market-fresh-row\" data-market-ticker=\"${esc(x.stock.ticker)}\"><span class=\"market-rebalance-rank\">${i+1}</span><span><strong>${esc(x.stock.ticker)} · ${esc(x.stock.name||'')}</strong><small>${tierLabel(x)} · ${euro(x.amount)} · ${x.existingValue>0?'reforço':'nova posição'} · conv. ${Math.round(x.conv)} · peso ${x.positionPct.toFixed(1)}% · setor ${x.sectorPct.toFixed(0)}%</small><small>${x.budgetMode==='soft budget'?'⚠ soft budget':''}${x.warnings?.length?`${x.budgetMode==='soft budget'?' · ':''}⚠ ${esc(x.warnings.slice(0,2).join(' · '))}`:''}</small></span><em>${x.score.toFixed(0)}</em></button>`).join('')}</div>`;\n"""
if old not in s: raise SystemExit('render fresh anchor missing')
s=s.replace(old,new,1)

old="""<label><span>Montante</span><input data-rebalance-amount type=\"number\" min=\"50\" step=\"50\" value=\"${Math.max(50,Math.min(1000,Math.round(defaultSource.value/50)*50||50))}\"></label>"""
new="""<label><span>Montante</span><input data-rebalance-amount type=\"number\" min=\"1\" max=\"${Math.max(1,Math.floor(defaultSource.value))}\" step=\"1\" value=\"${Math.max(1,Math.min(1000,Math.round(defaultSource.value)||1))}\"></label>"""
if old not in s: raise SystemExit('rebalancer amount anchor missing')
s=s.replace(old,new,1)

p.write_text(s)

p=Path('README.md'); s=p.read_text(); s="""## Vestra v5.8.1 — Candidate Fallbacks\n\n- Fresh Capital Planner e Assisted Rebalancer deixam de falhar silenciosamente quando nenhum ativo cumpre simultaneamente todos os filtros ideais.\n- Candidatos são classificados em Preferido, Aceitável com alertas e Apenas research; Risk Gate high/severe continua a ser exclusão dura.\n- Portfolio Targets continuam prioritários, mas existe um soft budget limitado quando todos os candidatos ficam bloqueados por pequenas ultrapassagens.\n- A interface mostra confiança baixa/ausente, valuation exigente, expectativas em deterioração e soft budget em vez de esconder o candidato.\n- Rebalancer deixa de sugerir um montante mínimo superior ao valor da posição de origem.\n- PWA cache: `vestra-cache-v54`.\n\n"""+s; p.write_text(s)

p=Path('sw.js'); s=p.read_text().replace('vestra-cache-v53','vestra-cache-v54'); p.write_text(s)
