from pathlib import Path

p=Path('market.js')
s=p.read_text(encoding='utf-8')
old='''${methods.length?`<div class="market-watchpoints">${methods.slice(0,4).map(x=>`<span>${esc(x.method)} · ${money(x.fair_value,s.currency)}</span>`).join('')}</div>`:''}</div><div class="market-detail-card"><h4>Múltiplos</h4>'''
new='''${methods.length?`<div class="market-watchpoints">${methods.slice(0,5).map(x=>`<span>${esc(x.method)} · ${money(x.fair_value,s.currency)}${n(x.weight)!=null?` · peso ${num(x.weight)}×`:''}</span>`).join('')}</div>`:''}<div class="market-score-layers"><p class="market-case-note"><strong>1 · De onde vem cada valor.</strong> Cada método pergunta a que preço esta empresa negociaria se o seu múltiplo ou yield convergisse para a mediana do próprio setor. Ex.: no P/E, fair value implícito = preço atual × P/E mediano do setor ÷ P/E da empresa.</p><p class="market-case-note"><strong>2 · Como se chega ao centro.</strong> Os métodos têm pesos diferentes conforme o modelo económico. O Vestra combina a média ponderada com a mediana das estimativas para reduzir o efeito de um método extremo. Nos modelos Geral e Tecnologia/Crescimento, Qualidade e Growth podem ajustar o centro, mas o ajuste total é limitado a ±12%.</p><p class="market-case-note"><strong>3 · Porque existe uma faixa.</strong> Com dois ou mais métodos a banda mínima é ±12%; com apenas um é ±18%. Se os métodos discordarem, a faixa alarga, até ao máximo de ±28%. Uma faixa larga significa maior incerteza, não maior upside.</p><p class="market-case-note"><strong>4 · Como nasce o sinal.</strong> “Undervalued” exige pelo menos +25% até ao fair value central; “Overvalued” começa em −20%. Entre estes limites a leitura é “Fair”. Risk Gate high/severe ou confidence score &lt;50 transforma o sinal em “Uncertain”, mesmo quando a estimativa numérica parece barata.</p><p class="market-case-note"><strong>5 · O que isto não é.</strong> Não é DCF, NAV inferido, target de analistas nem preço futuro previsto. É uma faixa peer-relative, dependente dos dados e dos comparáveis disponíveis.</p></div></div><div class="market-detail-card"><h4>Múltiplos</h4>'''
if s.count(old)!=1:
    raise SystemExit(f'valuation methods anchor mismatch: {s.count(old)}')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

t=Path('tests/test_market_valuation_explainability.py')
t.write_text('''from pathlib import Path\nimport unittest\n\nROOT=Path(__file__).resolve().parents[1]\n\nclass MarketValuationExplainabilityTests(unittest.TestCase):\n    @classmethod\n    def setUpClass(cls):\n        cls.market=(ROOT/'market.js').read_text(encoding='utf-8')\n\n    def test_methods_show_relative_weights(self):\n        self.assertIn('peso ${num(x.weight)}×', self.market)\n\n    def test_peer_relative_formula_is_explained(self):\n        self.assertIn('preço atual × P/E mediano do setor ÷ P/E da empresa', self.market)\n        self.assertIn('mediana do próprio setor', self.market)\n\n    def test_range_mechanics_are_explained(self):\n        self.assertIn('banda mínima é ±12%', self.market)\n        self.assertIn('apenas um é ±18%', self.market)\n        self.assertIn('máximo de ±28%', self.market)\n\n    def test_signal_thresholds_and_risk_override_are_explained(self):\n        self.assertIn('“Undervalued” exige pelo menos +25%', self.market)\n        self.assertIn('“Overvalued” começa em −20%', self.market)\n        self.assertIn('confidence score &lt;50', self.market)\n        self.assertIn('transforma o sinal em “Uncertain”', self.market)\n\n    def test_not_intrinsic_or_analyst_target(self):\n        self.assertIn('Não é DCF, NAV inferido, target de analistas nem preço futuro previsto', self.market)\n\nif __name__ == '__main__':\n    unittest.main(verbosity=2)\n''',encoding='utf-8')
