from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
market = ROOT / 'market.js'
test = ROOT / 'tests' / 'test_market_score_explanation.py'

text = market.read_text(encoding='utf-8')
old = """  function dimRows(s){\n    const dims=scoreDims(s);\n    return dims.map(([k,v])=>`<div class=\"market-dim\"><div><div class=\"market-dim__label\"><span>${k}</span><strong>${n(v)==null?'—':Math.round(v)}</strong></div><div class=\"market-bar\"><span style=\"width:${Math.max(0,Math.min(100,n(v)||0))}%\"></span></div></div><span></span></div>`).join('');\n  }\n"""
new = """  function scoreMetricValue(s,key,kind='pct'){\n    const value=n(s?.[key]);\n    if(value==null) return null;\n    if(kind==='num') return num(value);\n    if(kind==='compact') return compact(value);\n    if(kind==='multiple') return `${num(value)}×`;\n    return pct(value);\n  }\n\n  function pillarMetricSummary(s,label){\n    const defs={\n      'Qualidade':[['ROE','roe'],['ROA','roa'],['Margem líquida','profit_margin'],['Margem operacional','operating_margin'],['Margem bruta','gross_margin']],\n      'Crescimento':[['Receitas','revenue_growth'],['Lucros','earnings_growth'],['Lucros trimestrais','earnings_quarterly_growth']],\n      'Balanço':[['Current ratio','current_ratio','multiple'],['Quick ratio','quick_ratio','multiple'],['Debt / Equity','debt_to_equity','num'],['Net cash','net_cash','compact'],['Cobertura juros','interest_coverage','multiple']],\n      'Cash flow':[['FCF yield','fcf_yield'],['Cash flow operacional','operating_cash_flow','compact'],['Free cash flow','free_cash_flow','compact']],\n      'Valuation':[['P/E','trailing_pe','multiple'],['Forward P/E','forward_pe','multiple'],['P/B','price_to_book','multiple'],['EV/EBITDA','enterprise_to_ebitda','multiple'],['PEG','peg_ratio','multiple']],\n      'Execução':[['Receitas','revenue_growth'],['Lucros','earnings_growth'],['Margem operacional','operating_margin']],\n      'Qualidade dos lucros':[['Conversão caixa/lucro','cash_conversion_ratio','multiple'],['Accrual ratio','accrual_ratio'],['Margem FCF','fcf_margin']],\n      'Alocação de capital':[['Diluição YoY','diluted_shares_yoy'],['Buybacks último T','repurchases_last_quarter','compact'],['ROCE proxy','roce_proxy'],['Cobertura dividendo/FCF','dividend_fcf_coverage','multiple']],\n      'Estabilidade':[['Beta','beta','num']]\n    };\n    const metrics=defs[label]||[];\n    if(!metrics.length) return '';\n    const present=[]; let missing=0;\n    for(const [name,key,kind] of metrics){\n      const rendered=scoreMetricValue(s,key,kind||'pct');\n      if(rendered==null){ missing+=1; continue; }\n      present.push(`${esc(name)} <strong>${esc(rendered)}</strong>`);\n    }\n    const missingText=missing?` · ${missing} ${missing===1?'métrica em falta':'métricas em falta'}`:'';\n    return `<div class=\"market-dim__evidence\">${present.length?present.join(' · '):'Sem métricas-base disponíveis'}${missingText}</div>`;\n  }\n\n  function dimRows(s){\n    const dims=scoreDims(s);\n    return dims.map(([k,v])=>`<div class=\"market-dim\"><div><div class=\"market-dim__label\"><span>${k}</span><strong>${n(v)==null?'—':Math.round(v)}</strong></div><div class=\"market-bar\"><span style=\"width:${Math.max(0,Math.min(100,n(v)||0))}%\"></span></div>${pillarMetricSummary(s,k)}</div><span></span></div>`).join('');\n  }\n"""
if old not in text:
    raise SystemExit('dimRows anchor not found')
text = text.replace(old, new, 1)
market.write_text(text, encoding='utf-8')

test.write_text('''from pathlib import Path\nimport subprocess\nimport unittest\n\nROOT = Path(__file__).resolve().parents[1]\nMARKET = ROOT / "market.js"\n\nclass MarketScoreExplanationTests(unittest.TestCase):\n    def test_market_js_is_valid(self):\n        subprocess.run(["node", "--check", str(MARKET)], check=True, cwd=ROOT)\n\n    def test_pillars_expose_raw_metric_evidence(self):\n        text = MARKET.read_text(encoding="utf-8")\n        for token in (\n            "pillarMetricSummary",\n            "ROE", "ROA", "Margem operacional",\n            "Receitas", "Lucros trimestrais",\n            "Current ratio", "Cobertura juros",\n            "FCF yield", "Forward P/E", "EV/EBITDA",\n            "Conversão caixa/lucro", "Accrual ratio",\n            "Diluição YoY", "ROCE proxy", "Beta",\n            "métrica em falta",\n        ):\n            self.assertIn(token, text)\n\n    def test_explanation_does_not_change_score_math(self):\n        text = MARKET.read_text(encoding="utf-8")\n        self.assertIn("scoreDims(s)", text)\n        self.assertNotIn("s.score =", text)\n        self.assertNotIn("s.quality_pct =", text)\n\nif __name__ == "__main__":\n    unittest.main(verbosity=2)\n''', encoding='utf-8')
